name: wabi
region: sgp
services:

# Backend API and WebSocket server
- name: backend
  github:
    repo: AzureFoxStudios/wabi
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile.backend
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xs
  build_command: ""
  
  health_check:
    http_path: /health
  envs:
  - key: NODE_ENV
    value: production
    scope: RUN_AND_BUILD_TIME
  - key: PORT
    value: "3000"
    scope: RUN_AND_BUILD_TIME
  - key: FRONTEND_URL
    value: https://${APP_DOMAIN}
    scope: RUN_AND_BUILD_TIME
  - key: PUBLIC_URL
    value: https://${APP_DOMAIN}
    scope: RUN_AND_BUILD_TIME

# Frontend Nginx reverse proxy and static file server
- name: web
  github:
    repo: AzureFoxStudios/wabi
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile.frontend
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xs
  
  health_check:
    http_path: /health
  envs: []
